sudo: required
dist: trusty 
language: php
php :
  -7.1.9

branches: 
  only:
    -master #->Staging Server
    -develop  #-> DevServer
    
# sebelum melakukan atau eksekusi script
#install kebutuhan OS. ext: mod-php dll.
before_install:
- curl -LO https://storage.googleapis/kubernetes-release/release/$(curl -s https://storage/googleapis.com/kubernetes-release/release/stable.txt)/bin.linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl/usr/local/bin/kubectl
- kubectl

#pre execution
#testing dll
before_script:

#main execution
script: